# Generated by Django 3.0.2 on 2020-05-19 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='-')),
                ('thought', models.TextField(default='-')),
                ('picurl', models.TextField(default='-')),
                ('picname', models.TextField(default='-')),
                ('videourl', models.TextField(default='-')),
                ('videoname', models.TextField(default='-')),
                ('date', models.DateField(default=datetime.date.today)),
                ('share', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('love', models.IntegerField(default=0)),
            ],
        ),
    ]
