# Generated by Django 3.0.2 on 2020-05-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='-')),
                ('post_info', models.ForeignKey(default='-', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Post', verbose_name='POST')),
            ],
        ),
    ]
