# Generated by Django 3.0.2 on 2020-05-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='comment_num',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='love',
            new_name='love_num',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='share',
            new_name='share_num',
        ),
    ]
