# Generated by Django 3.0.6 on 2020-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200717_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usr_pic',
            field=models.TextField(default='-'),
        ),
    ]
