# Generated by Django 3.0.6 on 2020-07-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studentdetails_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Summary',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
