# Generated by Django 3.0.6 on 2020-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200718_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
