# Generated by Django 3.0.6 on 2020-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200718_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallmessage',
            name='color',
            field=models.TextField(default='orange', null=True),
        ),
    ]
