# Generated by Django 3.0.6 on 2020-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_wallmessage_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem_reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='-')),
                ('details', models.TextField(default='-')),
            ],
        ),
    ]
